language: node_js
os: osx # travis linux lacks IPv6 support
node_js:
  - "10"
  - "12"
  - "14"

script:
  # this builds the module, if it fails the build did not pass
  - npm install
  - npm run prettier:check
  - npm run lint
  - npm run ts:check
  - npm run build
  - npm test

before_deploy:
  - npm run docs
  - npm run docs:predeploy
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GH_TOKEN
    on:
      tags: true
      branch: master
      node_js: "14"

  - provider: releases
    api_key: $GH_TOKEN
    skip_cleanup: true
    file_glob: true
    file: "netlinkwrapper-*.tgz"
    on:
      tags: true
      branch: master
      node_js: "14"

  - provider: npm
    skip_cleanup: true
    email: "jacob.t.fischer@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
      branch: master
      node_js: "14"
